name: Auto-Update Nightly Build

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  calculateDependencies:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.github_token }}
    outputs:
      dependencies: ${{ steps.dependencyTool.outputs.DEPENDENCIES }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'PalladioSimulator/Palladio-Build-DependencyTool'
          ref: '0.0.2'
      - name: Set up JDK
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build Palladio-Build-DependencyTool
        run: mvn -DskipTests clean package
      - name: Run Palladio-Build-DependencyTool
        id: dependencyTool
        run: echo "DEPENDENCIES=$(java -jar target/deploy/dependencytool.jar -ri Palladio-Build-UpdateSite -ii -us 'https://updatesite.palladio-simulator.com/' -rrf .github/workflows/build.yml -j -o dependencies PalladioSimulator)" >> "$GITHUB_OUTPUT"

  generateNightlyBuild:
    runs-on: ubuntu-latest
    needs: calculateDependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install -C scripts/generate_nightly
      - name: Generate nightly.yml
        run: poetry run -C scripts/generate_nightly python -m generate_nightly
        env:
          DEPENDENCIES: ${{ needs.calculateDependencies.outputs.dependencies }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PR_TOKEN }}
          commit-message: "auto-update nightly build"
          title: "auto-update nightly build"
          labels: auto-update
          branch: chore/update-build
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
